//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionTargetRef) DeepCopyInto(out *ActionTargetRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionTargetRef.
func (in *ActionTargetRef) DeepCopy() *ActionTargetRef {
	if in == nil {
		return nil
	}
	out := new(ActionTargetRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceRecord) DeepCopyInto(out *MaintenanceRecord) {
	*out = *in
	in.StartedAt.DeepCopyInto(&out.StartedAt)
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceRecord.
func (in *MaintenanceRecord) DeepCopy() *MaintenanceRecord {
	if in == nil {
		return nil
	}
	out := new(MaintenanceRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceWindowSpec) DeepCopyInto(out *MaintenanceWindowSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceWindowSpec.
func (in *MaintenanceWindowSpec) DeepCopy() *MaintenanceWindowSpec {
	if in == nil {
		return nil
	}
	out := new(MaintenanceWindowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresMemoryPolicy) DeepCopyInto(out *PostgresMemoryPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresMemoryPolicy.
func (in *PostgresMemoryPolicy) DeepCopy() *PostgresMemoryPolicy {
	if in == nil {
		return nil
	}
	out := new(PostgresMemoryPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PostgresMemoryPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresMemoryPolicyList) DeepCopyInto(out *PostgresMemoryPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PostgresMemoryPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresMemoryPolicyList.
func (in *PostgresMemoryPolicyList) DeepCopy() *PostgresMemoryPolicyList {
	if in == nil {
		return nil
	}
	out := new(PostgresMemoryPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PostgresMemoryPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresMemoryPolicySpec) DeepCopyInto(out *PostgresMemoryPolicySpec) {
	*out = *in
	out.MemoryMin = in.MemoryMin.DeepCopy()
	out.MemoryMax = in.MemoryMax.DeepCopy()
	if in.InitialMemory != nil {
		x := in.InitialMemory.DeepCopy()
		out.InitialMemory = &x
	}
	out.MaintenanceWindow = in.MaintenanceWindow
	out.SafetyGates = in.SafetyGates
	if in.PostActions != nil {
		in, out := &in.PostActions, &out.PostActions
		*out = make([]PostActionSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresMemoryPolicySpec.
func (in *PostgresMemoryPolicySpec) DeepCopy() *PostgresMemoryPolicySpec {
	if in == nil {
		return nil
	}
	out := new(PostgresMemoryPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresMemoryPolicyStatus) DeepCopyInto(out *PostgresMemoryPolicyStatus) {
	*out = *in
	if in.MemoryTarget != nil {
		x := in.MemoryTarget.DeepCopy()
		out.MemoryTarget = &x
	}
	if in.CurrentMemory != nil {
		x := in.CurrentMemory.DeepCopy()
		out.CurrentMemory = &x
	}
	if in.MaintenanceHistory != nil {
		in, out := &in.MaintenanceHistory, &out.MaintenanceHistory
		*out = make([]MaintenanceRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresMemoryPolicyStatus.
func (in *PostgresMemoryPolicyStatus) DeepCopy() *PostgresMemoryPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(PostgresMemoryPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostActionSpec) DeepCopyInto(out *PostActionSpec) {
	*out = *in
	out.Target = in.Target
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostActionSpec.
func (in *PostActionSpec) DeepCopy() *PostActionSpec {
	if in == nil {
		return nil
	}
	out := new(PostActionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SafetyGatesSpec) DeepCopyInto(out *SafetyGatesSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SafetyGatesSpec.
func (in *SafetyGatesSpec) DeepCopy() *SafetyGatesSpec {
	if in == nil {
		return nil
	}
	out := new(SafetyGatesSpec)
	in.DeepCopyInto(out)
	return out
}
